import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline/promises";
import { config, requireUser } from "./config.js";
import { banner, dim, ok, reset, section, warn } from "./ui.js";
import { runDoctor } from "./doctor.js";

function loadEnv(): Record<string, string> {
  const out: Record<string, string> = {};
  if (!existsSync(".env")) return out;
  for (const line of readFileSync(".env", "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

async function prompt(rl: Awaited<ReturnType<typeof createInterface>>, label: string, current = ""): Promise<string> {
  const value = await rl.question(`${label}${current ? ` [${current}]` : ""}: `);
  return value.trim() || current;
}

export async function runOnboard(): Promise<void> {
  banner();
  section("Sentry setup wizard");
  console.log(`  ${dim}Answer the prompts. Existing values are shown in brackets — press Enter to keep them.${reset}`);
  console.log(`  ${dim}Press Ctrl+C to abort at any time.${reset}`);

  const existing = loadEnv();
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  const khApiKey = await prompt(rl, "KeeperHub API key (kh_… from app.keeperhub.com → Settings → API keys)", existing.KH_API_KEY ?? "");
  const userAddress = await prompt(rl, "Aave V3 user address on Base (0x…)", existing.USER_ADDRESS ?? "");
  const hfThreshold = await prompt(rl, "Health-factor defend threshold", existing.HF_THRESHOLD ?? String(config.hfThreshold));
  const repayAmountUsdc = await prompt(rl, "Partial repay amount (USDC)", existing.REPAY_AMOUNT_USDC ?? String(config.repayAmountUsdc));
  const openaiApiKey = await prompt(rl, "OpenAI API key (optional — enables LLM reasoning)", existing.OPENAI_API_KEY ?? "");
  rl.close();

  if (!khApiKey) warn("No API key given — onboarding will still work for read-only demo, but not defend.");
  if (!userAddress) warn("No user address given — pass one to `npm run demo -- 0x…` later.");

  const body = [
    "# Sentry environment (generated by `npm run onboard`)",
    `KH_API_KEY=${khApiKey}`,
    `USER_ADDRESS=${userAddress}`,
    `HF_THRESHOLD=${hfThreshold}`,
    `REPAY_AMOUNT_USDC=${repayAmountUsdc}`,
    "NETWORK=8453",
    openaiApiKey ? `OPENAI_API_KEY=${openaiApiKey}` : "# OPENAI_API_KEY=",
    "# ANTHROPIC_API_KEY=",
    "DRY_RUN=false",
    "",
    "# Run `npm run doctor` to verify.",
  ].join("\n");
  writeFileSync(".env", body, "utf8");
  ok(".env written");

  section("Next steps");
  console.log(`  1. ${dim}npm run demo${reset}            — see a live health verdict (read-only, free)`);
  console.log(`  2. ${dim}npm run doctor${reset}          — verify every prerequisite`);
  console.log(`  3. ${dim}npm run loop${reset}            — monitor and defend autonomously`);
  console.log(`  4. ${dim}npm run defend${reset}          — force a defensive repay (needs a funded position)`);
  console.log("");
  console.log(`  ${dim}Open a position: https://app.aave.com/?marketName=proto_base_v3${reset}`);
  console.log(`  ${dim}Connect the wallet for writes: app.keeperhub.com → Wallet integrations${reset}\n`);

  await runDoctor(requireUser() || undefined).catch(() => undefined);
}
